var templates = { 
   "stock_entry_in_list":
		['<td class="update_target info {tag} {classes}" val-type="{tag}" stock="{stock}" index="{index}" port_id="{port_id}">{tagValue}</td>'].join(''),
   "view_portfolio_page" : ['<div id="view_pf" class="page panel view_pf {pf_type}" title="Portfolio" button="refreshBtn">',
                              '<div id="summary_container">{summary}</div>',
                                '<ul class="tabs two_tabs">',
                                        '<li class="viewPerformance tab first" view="viewPerformance" onclick=""><a>Gain/Loss</a></li>',
                                        '<li class="viewPosition tab last" view="viewPosition" onclick=""><a>Position</a></li>',
                                '</ul>',
                                '<div id="stocks_container">{stocks}</div>',
                                '<div class="tip">*Turn your phone to landscape mode to display more info</div>',
                                '<table class="buttons toolbar">',
                                      '<tr>',
                                              '<td><button class="pageLink flat_button edit_cash">Edit Cash Balance</button></td>',
                                              '<td><button class="pageLink flat_button rename">Rename</button></td>',
                                      '</tr><tr>',
                                              '<td><button class="pageLink flat_button record_buy">Record a Buy</button></td>',
                                              '<td><button class="pageLink flat_button rename record_sell">Record a Sell</button></td>',
                                      '</tr><tr>',
                                              '<td><button class="pageLink flat_button edit_positions">Edit Positions</button></td>',
                                '</tr></table>',
                              '<div class="chart hidden"><div class="content"></div></div>',
                            '</div>'].join(''),
    "news_page" : '<div id="news" class="page" title="News"><ul class="block rounded news_container hide_extra_items"></ul></div>',
    "edit_portfolio_page" : ['<div id="editPortfolio" class="page panel" button="save_btn" title="New Portfolio">',
                             	 '<div id="content" class="content"></div>',
	                             '<table class="add_position input_group"><tr><td class="icon"><a class="add_icon" onclick=""></a></td>',
	                             '<td><div class="add_position flat_button rounded_block"><label>Add a new position</label></div></td></tr></table>',
	                             '<div class="delete_button red_button"><label>Delete Portfolio</label></div>',
                             '</div>'].join(""),
    "edit_portfolio" :   [  '<fieldset class="group port_info input">',
                                '<div class="row name">',
                                    '<label>Name</label>',
                                    '<input value="{name}" placeholder="Portfolio name">',
                                '</div>',
                                '<div class="row cash">',
                                    '<label>Cash</label>',
                                    '<input value="{cash}" type="number" placeholder="Enter cash balance" name="Cash">',
                                '</div>',
                                '<div class="row show_state"><label>Show on Home Page</label><div class="pf_toggle toggle" onclick="" toggled="{show_state}"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div></div>',
                                '<div class="row include_total"><label>Include in Total Assets</label><div class="pf_toggle toggle" onclick="" toggled="{aggregate_state}"><span class="thumb"></span><span class="toggleOn">yes</span><span class="toggleOff">no</span></div></div>',
                            '</fieldset>'].join(''),
    "news_item" : '<li class="arrow news_item {hidden}"><a href="{link}" target="_blank"><div>{title} <span class="time">{date}</span></div></a></li>',
    "new_stock" : ['<table class="input_group" id="{id}"><tr><td class="icon"><a class="delete" onclick=""></a></td><td><fieldset class="stock_info input group" id="{id}">',
                        '<div class="row symbol">',
                            '<label>Symbol</label>',
                            '<input value="{symbol}" type="text" placeholder="Symbol ticker">',
                        '</div>',
                        '<div class="row shares">',
                            '<label>Shares</label>',
                            '<input value="{shares}" type="" placeholder="Number of shares" name="Shares">',
                        '</div>',
                        '<div class="row paid">',
                            '<label>Price</label>',
                            '<input value="{paid}" type="" placeholder="Purchase price" name="Price">',
                        '</div>',
                        '<div class="row date">',
                            '<label>Date</label>',
                            '<input value="{date}" type="date" placeholder="Trade date"  name="Date">',
                        '</div>',
                        '<div class="row note">',
                            '<label>Notes</label>',
                            '<input value="{note}" placeholder="Notes">',
                        '</div>',
                    '</fieldset></td></tr></table>'].join(''),
    "edit_stock_dialog_lot" : '<li><button class="whitebutton multi" positionId={id}>{shares} {symbol} @ ${buy}</button><li>',
    "trans_fields": [	'<div class="row options">',
                                 '<label>Type of Options</label>',
                                 '<div id="putOrCall" class="toggle" name="stockOrOptions" onclick="" toggled="{isPut}"><span class="thumb"></span><span class="toggleOn">Put</span><span class="toggleOff">Call</span></div>',
                              '</div>',
                        '<li><input type="text" class="symbol" placeholder="Symbol" value="{symbol}"></li>',
                        '<li><input type="text" class="shares" placeholder="Number of Shares" value="{shares}"></li>',
                        '<li><input type="text" class="buy" placeholder="Transaction Price" value="{buy}"></li>',
                        '<li><select class="options strike_date"><option>Loading...</option></select></li>',                        
                        '<li><select class="options strike_price"><option>Select an expiration date</option></select></li>',
                        '<li><input type="text" class="comm" placeholder="Commission" value="{comm}"></li>',
                        '<li><input type="text" class="date" placeholder="Transaction Date" value="{date}"></li>',
                        '<li><input type="text" class="note" placeholder="Notes" value="{note}"></li>'].join(""),
    "new_trans_dialog" : [
                           '<fieldset class="content {stock_trans}" positionId="{positionId}">',
                              '<h1 class="title">{title}</h1>',
                              '<a class="button leftButton" type="cancel">Cancel</a>',
                              '<a class="button blueButton done_btn edit new" type="cancel">Save</a>',
                              '<div class="row">',
                                 '<label>This is a Options trade</label>',
                                 '<div id="stockOrOptions" class="toggle" name="stockOrOptions" onclick="" toggled="false"><span class="thumb"></span><span class="toggleOn">Yes</span><span class="toggleOff">No</span></div>',
                              '</div>',
                              '<div class="row options">',
                                 '<label>Near the money</label>',
                                 '<div id="nearMoney" class="toggle" name="nearMoney" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">Yes</span><span class="toggleOff">No</span></div>',
                              '</div>',
                               '{trans_fields}',
                           '</fieldset>'
                              ].join(""),
    "edit_stock_dialog" : [
						'<fieldset class="content {type}" positionId="{positionId}">',
						    '<h1 class="title edit">Edit Position</h1>',
						    '<h1 class="title multi">Select A Lot</h1>',
						    '<a class="button leftButton" type="cancel">Cancel</a>',
						    '<a class="button blueButton done_btn edit" type="cancel">Save</a>',
						    '{lots_info}',
						    '{trans_fields}',
						    '<button class="delete redbutton edit">Sell Position</button>',
						'</fieldset>'
                           ].join(""),
	"position_item_container" : [
	         		   '<table class="positions_root" portId="{port_id}">',
					        '<tr class="row">',
					            '<th class="">Shares</td>',
					            '<th class="">Paid</td>',
					            '<th class="landscape_col">Portfolio</td>',
					            '<th class="">Date</td>',
					        '</tr>',
					        '{lots}',
				        '</table>',
	            ].join(""),
    "position_item" : [
		            '<tr class="row position_item" positionId="{id}">',
		                '<td class="value shares">{shares}</td>',
		                '<td class="value price">${buy}</td>',
		                '<td class="value date landscape_col">{port_name}</td>',
		                '<td class="value date forward">{date}</td>',
		            '</tr>'
		            ].join(""),	
    "position_item_edit" : [
		            '<tr class="row position_item" positionId="{id}">',
	                	'<td class="icon"><a class="delete" onclick=""></a></td>',
		                '<td class="value shares">{shares}</td>',
		                '<td class="value price">${buy}</td>',
		                '<td class="value date landscape_col">{note}</td>',
		                '<td class="value date forward">{date}</td>',
		            '</tr>'
		            ].join("")
};

