
var templates = { 
   "home_account_summary": 
       ['<div class="port_summary {classes}" port_id="{port_id}" {clickable}>',
            '<div class="round_block" >',
                '<div class="block header lighter_bg">',
                    '<h2 class="name">{port_name}<span class="market-value value right-align">{market_value}</span></h2>', 
                '</div>',
                '<div class="block loading last_block">Loading...</div>',
                '<div class="block content hidden">',
                    '<table class="content row">',
                        '<tr class="cash_balance">',
                            '<td><div class="label">Cash Balance</div></td>',
                            '<td><div class="value info">{cash}</div></td>',
                        '</tr>',
                        '<tr class="gain">',
                            '<td><div class="label">Gain/Loss</div></td>',
                            '<td><div class="value info negative">{gain}</div></td>',
                        '</tr>',
                        '<tr class="value-delta">',
                            '<td><div class="label">Day\'s Change</td>',
                            '<td><div class="value info">{value_delta}</div></td>',
                        '</tr>',
                    '</table>',
                '</div>',
            '</div>',
        '</div>'].join("\r\n"),
    "feature_block": ['<div class="round_block color_bg entry" stock="{symbol}" shares="{shares}" noPrefix="{noPrefix}">', 
	                '<div class="block lighter_bg header">',
	                	'<span class="name">{name}</span>',
	                	'<span class="value right-align price"></span>',
	                '</div>',
	                '<div class="block content positive">',
	                	'<span class="change"></span> ',
	                	'<span class="value right-align percent-change"></span>',
	                '</div>',
	            '</div>'].join(""),
	"stock_entry_in_list":
		['<td class="update_target info {tag} {classes}" val-type="{tag}" stock="{stock}" index="{index}" port_id="{port_id}">{tagValue}</td>'].join(''),
	"view_portfolio_page" : ['<div id="view_pf" class="page panel view_pf {pf_type}" title="Portfolio" button="refreshBtn">',
								'<div id="summary_container">{summary}</div>',
								  '<ul class="tabs two_tabs">',
									  '<li class="viewPerformance tab first" view="viewPerformance" onclick=""><a>Gain/Loss</a></li>',
									  '<li class="viewPosition tab last" view="viewPosition" onclick=""><a>Position</a></li>',
								  '</ul>',
								  '<div id="stocks_container">{stocks}</div>',
								  '<div class="tip">*Turn your phone to landscape mode to display more info</div>',
								  '<table class="buttons toolbar">',
								  	'<tr>',
										'<td><button class="pageLink flat_button edit_cash">Edit Cash Balance</button></td>',
										'<td><button class="pageLink flat_button rename">Rename</button></td>',
									'</tr><tr>',
										'<td><button class="pageLink flat_button record_buy">Record a Buy</button></td>',
										'<td><button class="pageLink flat_button rename record_sell">Record a Sell</button></td>',
									'</tr><tr>',
										'<td><button class="pageLink flat_button edit_positions">Edit Positions</button></td>',
								  '</tr></table>',
								  '<div class="chart hidden"><div class="content"></div></div>',
                            '</div>'].join(''),
    "news_page" : '<div id="news" class="page" title="News"><ul class="block rounded news_container hide_extra_items"></ul></div>',
    "edit_portfolio_page" : ['<div id="editPortfolio" class="page panel" button="save_btn" title="New Portfolio">',
                             	 '<div id="content" class="content"></div>',
	                             '<table class="add_position input_group"><tr><td class="icon"><a class="add_icon" onclick=""></a></td>',
	                             '<td><div class="add_position flat_button rounded_block"><label>Add a new position</label></div></td></tr></table>',
	                             '<div class="delete_button red_button"><label>Delete Portfolio</label></div>',
                             '</div>'].join(""),
    "edit_portfolio" :   [  '<fieldset class="group port_info input">',
                                '<div class="row name">',
                                    '<label>Name</label>',
                                    '<input value="{name}" placeholder="Portfolio name">',
                                '</div>',
                                '<div class="row cash">',
                                    '<label>Cash</label>',
                                    '<input value="{cash}" type="number" placeholder="Enter cash balance" name="Cash">',
                                '</div>',
                                '<div class="row show_state"><label>Show on Home Page</label><div class="pf_toggle toggle" onclick="" toggled="{show_state}"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div></div>',
                                '<div class="row include_total"><label>Include in Total Assets</label><div class="pf_toggle toggle" onclick="" toggled="{aggregate_state}"><span class="thumb"></span><span class="toggleOn">yes</span><span class="toggleOff">no</span></div></div>',
                            '</fieldset>'].join(''),
    "news_item" : '<li class="arrow news_item {hidden}"><a href="{link}" target="_blank"><div>{title} <span class="time">{date}</span></div></a></li>',
    "new_stock" : ['<table class="input_group" id="{id}"><tr><td class="icon"><a class="delete" onclick=""></a></td><td><fieldset class="stock_info input group" id="{id}">',
                        '<div class="row symbol">',
                            '<label>Symbol</label>',
                            '<input value="{symbol}" type="text" placeholder="Symbol ticker">',
                        '</div>',
                        '<div class="row shares">',
                            '<label>Shares</label>',
                            '<input value="{shares}" type="" placeholder="Number of shares" name="Shares">',
                        '</div>',
                        '<div class="row paid">',
                            '<label>Price</label>',
                            '<input value="{paid}" type="" placeholder="Purchase price" name="Price">',
                        '</div>',
                        '<div class="row date">',
                            '<label>Date</label>',
                            '<input value="{date}" type="date" placeholder="Trade date"  name="Date">',
                        '</div>',
                        '<div class="row note">',
                            '<label>Notes</label>',
                            '<input value="{note}" placeholder="Notes">',
                        '</div>',
                    '</fieldset></td></tr></table>'].join(''),
    "edit_stock_dialog_lot" : '<li><button class="whitebutton multi" positionId={id}>{shares} {symbol} @ ${buy}</button><li>',
    "trans_fields": [		'<li><input type="text" class="symbol" placeholder="Symbol" value="{symbol}"></li>',
   						    '<li><input type="text" class="shares" placeholder="Number of Shares" value="{shares}"></li>',
   						    '<li><input type="text" class="buy" placeholder="Transaction Price" value="{buy}"></li>',
   						    '<li><input type="text" class="comm" placeholder="Commission" value="{comm}"></li>',
   						    '<li><input type="text" class="date" placeholder="Transaction Date" value="{date}"></li>',
   						    '<li><input type="text" class="note" placeholder="Notes" value="{note}"></li>'].join(""),
    "new_trans_dialog" : [
   						'<fieldset class="content" positionId="{positionId}">',
   						    '<h1 class="title">{title}</h1>',
   						    '<a class="button leftButton" type="cancel">Cancel</a>',
   						    '<a class="button blueButton done_btn edit new" type="cancel">Save</a>',
   						    '{trans_fields}',
   						'</fieldset>'
                              ].join(""),
    "edit_stock_dialog" : [
						'<fieldset class="content {type}" positionId="{positionId}">',
						    '<h1 class="title edit">Edit Position</h1>',
						    '<h1 class="title multi">Select A Lot</h1>',
						    '<a class="button leftButton" type="cancel">Cancel</a>',
						    '<a class="button blueButton done_btn edit" type="cancel">Save</a>',
						    '{lots_info}',
						    '{trans_fields}',
						    '<button class="delete redbutton edit">Sell Position</button>',
						'</fieldset>'
                           ].join(""),
	"position_item_container" : [
	         		   '<table class="positions_root" portId="{port_id}">',
					        '<tr class="row">',
					            '<th class="">Shares</td>',
					            '<th class="">Paid</td>',
					            '<th class="landscape_col">Note</td>',
					            '<th class="">Date</td>',
					        '</tr>',
					        '{lots}',
				        '</table>',
	            ].join(""),
	            /*
	"position_port_item" : [
	    	                '<tr class="row {selected}" port_id="{port_id}" onclick="">',
	    	                    '<td>{port_name}</td>',
	    	                    '<td class="right_align">{shares} shares</td>',
	    	                    '<td class="right_align">{value}</td>',
	    	                '</tr>'
	                        ].join(""),
	                        */
    "position_item_edit" : [
		            '<tr class="row position_item" positionId="{id}">',
	                	'<td class="icon"><a class="delete" onclick=""></a></td>',
		                '<td class="value shares">{shares}</td>',
		                '<td class="value price">${buy}</td>',
		                '<td class="value date landscape_col">{note}</td>',
		                '<td class="value date forward">{date}</td>',
		            '</tr>'
		            ].join(""), 
    "position_item" : [
		            '<tr class="row position_item" positionId="{id}">',
		                '<td class="value shares">{shares}</td>',
		                '<td class="value price">${buy}</td>',
		                '<td class="value date landscape_col">{note}</td>',
		                '<td class="value date forward">{date}</td>',
		            '</tr>'
		            ].join(""),		                
    "settings_toggleShowHidePort" : '<li class="block arrow {hidden}" port_id="{port_id}" onclick="">{port_name}</li>',
    "settings_page" : [                
                    '<div id="settings" class="page panel" title="Settings" class="panel iui">',
                        '<h2>Change Your Portfolio Settings</h2>',            
                        '<ul class="toggle_portfolio round_block"></ul>', 
                        '<br><br><h2>Portfolio Summary Settings</h2>', 
                        '<fieldset class="home_group group">',
                            '<div class="row hidden">',
                                '<label>Auto refresh every 30 seconds </label>',
                                '<div class="toggle" name="autoRefreshInterval" onclick="" toggled="false"><span class="thumb"></span><span class="toggleOn">auto</span><span class="toggleOff">off</span></div>',
                            '</div>',
                            '<div class="row">',
                                '<label>Show Gain/Loss</label>',
                                '<div class="toggle" name="hideHomeSumGain" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div>',
                            '</div>',
                            '<div class="row hidden">',
                                '<label>Show Day\'s Value Change</label>',
                                '<div class="toggle" name="hideHomeSumValueChange" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div>',
                            '</div>',
                            '<div class="row">',
                                '<label>Show Cash Balance</label>',
                                '<div class="toggle" name="hideHomeSumCash" onclick="" toggled="false"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div>',
                            '</div>',
                            '<div class="row hidden">',
                                '<label>Show News Headlines</label>',
                                '<div class="toggle" name="hideHomeTopNews" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div>',
                            '</div>',
                            '<div class="row hidden">',
                                '<label>Show Movers & Shakers</label>',
                                '<div class="toggle" name="hideHomeMovers" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">show</span><span class="toggleOff">hide</span></div>',
                            '</div>',
                        '</fieldset> ',       
                        '<br><br><h2>Combine positions of same stock</h2>', 
                        '<fieldset class="group">',
	                        '<div class="row">',
		                        '<label>Combine positions</label>',
		                        '<div class="toggle" name="expandPositions" onclick="" toggled="true"><span class="thumb"></span><span class="toggleOn">yes</span><span class="toggleOff">no</span></div>',
		                    '</div>',
                        '</fieldset> ',     
                    '</div>'].join("")
};

